INSERT INTO ANIMAL(ID, NAME, AGE, TYPE, GENDER, HEALTH_STATUS) VALUES
 (1,    'Axel',   5, 'DOG',     'MALE',     'HEALTHY'),
 (2,    'Roksa',  1, 'DOG',     'FEMALE',   'SICK'),
 (3,    'Hektor', 3, 'CAT',     'MALE',     'RECOVERED'),
 (4,    'Bella',  3, 'DOG',     'FEMALE',   'HEALTHY'),
 (5,    'Chrupek',2, 'RABBIT',  'MALE',     'HEALTHY'),
 (6,    'Dino',   6, 'BIRD',    'MALE',     'DEAD'),
 (7,    'Ara',    3, 'BIRD',    'FEMALE',   'HEALTHY'),
 (8,    'Rex',    3, 'DOG',     'MALE',     'HEALTHY'),
 (9,    'Nemo',   2, 'FISH',    'MALE',     'NOT_EXAMINED'),
 (10,   'Tosii',  5, 'RABBIT',  'FEMALE',   'HEALTHY'),
 (11,   'Baton',  1, 'CAT',     'MALE',     'UNDER_OBSERVATION'),
 (12,   'Droopy', 3, 'CAT',     'MALE',     'SICK'),
 (13,   'Ariel',  1, 'BIRD',    'FEMALE',   'HEALTHY'),
 (14,   'Cezar',  2, 'DOG',     'MALE',     'HEALTHY'),
 (15,   'Ciri',   7, 'DOG',     'FEMALE',   'HEALTHY'),
 (16,   'Karmel', 2, 'DOG',     'MALE',     'RECOVERED'),
 (17,   'Teo',    5, 'CAT',     'MALE',     'HEALTHY'),
 (18,   'Yuppi',  6, 'HAMSTER', 'FEMALE',   'NOT_EXAMINED'),
 (19,   'Frunia', 1, 'RABBIT',  'FEMALE',   'HEALTHY'),
 (120,  'Borys',  2, 'DOG',     'MALE',     'SICK');
